### ISSUE TITLE
'svg.wavedrom.com' doesn't seem to support config

### ISSUE THREAD

**Issue by K4zuki** [wavedrom/lambda#8]
Please describe your system environment before submitting your Issue.

- MacOS 10.15.6
- Chrome 85.0.4183.83

---

- When input following code on GitHub comment, `config` doesn't give effect, i.e. single lane or default skin is applied.

```html
<img src="https://svg.wavedrom.com/{config:{bits: '32', lanes: '2'},reg: [{name: 'a', bits: 8},{name: 'b', bits: 8},{name: 'c', bits: 1,type:2}]}"/>
<img src="https://svg.wavedrom.com/{config:{skin:'narrow'},signal:[{name:'clk',wave:'p......'},{name:'bus',wave:'x.34.5x',data:'head body tail'},{name:'wire',wave:'0.1..0.'}]}"/>
```
<img src="https://svg.wavedrom.com/{config:{bits: '32', lanes: '2'},reg: [{name: 'a', bits: 8},{name: 'b', bits: 8},{name: 'c', bits: 1,type:2}]}"/>
<img src="https://svg.wavedrom.com/{config:{skin:'narrow'},signal:[{name:'clk',wave:'p......'},{name:'bus',wave:'x.34.5x',data:'head body tail'},{name:'wire',wave:'0.1..0.'}]}"/>

**Comment by K4zuki** [comment]
@drom thanks for the fix. bitfield rendered as expected now, but the skin is still not applied.

**Comment by drom** [comment]
is it better now?

**Comment by K4zuki** [comment]
Thanks again for the update.
It is better now but continues with certain code

This doesn't work:
```
{config:{skin:'narrow'},signal:[{name:'clk',wave:'p......'},{name:'bus',wave:'x.34.5x'},{name:'wire',wave:'0.1..0.'}]}
```

This works:
```
{config:{skin:'narrow'},signal:[{name:'clk',wave:'p......'},{name:'wire',wave:'0.1..0.'}]}
{config:{skin:'narrow'},signal:[{name:'clk',wave:'p......'},{name:'bus',wave:'x.34.5x'}]}
{config:{skin:'narrow'},signal:[{name:'clk',wave:'p......'},{name:'wire',wave:'0.1..0.'},{name:'bus',wave:'x.34.5x'}]}
```

**Comment by drom** [comment]
I think some of the images got cached and will show the same old image instead of rerendering. Please change some insignificant character to see new image.

**Comment by drom** [comment]
consider fixed
